name: "CI"

on:
    push:
        paths-ignore: ".github/workflows/ci-basics.yml"
    workflow_dispatch: ~

jobs:
    php-cs-fixer:
        name: "PHP-CS-Fixer"
        runs-on: ubuntu-latest
        steps:
          -   name: "Checkout Repository"
              uses: actions/checkout@v4
            # PHP 8.1
          - name: "Run PHP-CS-Fixer"
            uses: erkenes/php-cs-fixer-action@php8.1-1.0.0
    deps:
        name: "Install dependencies"
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql
                env: 
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: app
                    MYSQL_ROOT_HOST: '%'
                ports:
                    - 3306:3306
        steps:
          -   name: "Checkout Repository"
              uses: actions/checkout@master
          -   name: "Setup Php Enviroment"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  tools: composer
          -   name: "Check database healthy"
              run: nc -zv localhost 3306
          -   name: "Install Packages"
              run: |
                export APP_ENV=test
                composer install --prefer-dist --no-interaction --no-progress
          -   name: "Run Migrations"
              run: php bin/console d:m:m
              env:
                DATABASE_HOST: 127.0.0.1
                DATABASE_NAME: app
                DATABASE_PASSWORD: password
          -   name: "Start Server"
              run: |
                php bin/console
                php -S 127.0.0.1:8080 -t public &
                sleep 2
                nc -zv localhost 8080