name: "CI"

on:
    push:
        paths-ignore: ".github/workflows/ci-basics.yml"
    workflow_dispatch: ~

jobs:
    deps:
        name: "Install dependencies"
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout Repository"
            uses: actions/checkout@v4
          - run: ls