name: "CI"

on:
    push:
        paths-ignore: ".github/workflows/ci-basics.yml"
    workflow_dispatch: ~

jobs:
    deps:
        name: "Install dependencies"
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql
                env: 
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: app
                ports:
                    - 3306:3306
        steps:
          -   name: "Checkout Repository"
              uses: actions/checkout@master
          -   name: "Setup Php Enviroment"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  tools: composer
          -   name: "Check database healthy"
              run: nc -zv localhost 3306
          -   name: "Install Packages"
              run: |
                export APP_ENV=test
                composer install --prefer-dist --no-interaction --no-progress