name: "CI"

on:
    push:
        paths-ignore: ".github/workflows/ci-basics.yml"
    workflow_dispatch: ~

jobs:
    deps:
        name: "Install dependencies"
        runs-on: ubuntu-latest
        steps:
          -   name: "Checkout Repository"
              uses: actions/checkout@master
          -   name: "Setup Php Enviroment"
              uses: shivammathur/setup-php@v2.31.1
              with:
                  php-version: '8.1'
                  tools: composer
          -   name: "Install Packages"
              run: |
                export APP_ENV=test
                composer install --prefer-dist --no-interaction --no-progress